# Generated by Django 4.2.16 on 2024-09-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_post_video_url_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerresponse',
            old_name='author',
            new_name='client',
        ),
    ]
