# Generated by Django 4.2.16 on 2024-09-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_author_offerresponse_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerresponse',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
